name: Test changes
on:
  push:
    branches:
      - 'main'

jobs:
  cache-and-install:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Install Node.js
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2
        name: Install dependencies
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - run: pnpm install
        name: Install dependencies

      - run: pnpm test
        name: Test

      - uses: codecov/codecov-action@v3
